spring.application.name=CryptoCurrency_Project

spring.datasource.url=jdbc:sqlite:/home/ahibou/IdeaProjects/CryptoCurrency_Project/crypto_database.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

api.coincap.bearer-token=Bearer 57b97350-f365-4cea-9d27-3a1c86ed172a

#curl -H "Authorization: Bearer 57b97350-f365-4cea-9d27-3a1c86ed172a" https://api.coincap.io/v2/assets

