spring.application.name=CryptoCurrency_Project

spring.datasource.url=jdbc:sqlite:crypto_database.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

api.coincap.bearer-token=Bearer 57b97350-f365-4cea-9d27-3a1c86ed172a

#curl -H "Authorization: Bearer 57b97350-f365-4cea-9d27-3a1c86ed172a" https://api.coincap.io/v2/assets


spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=528138a36fa465
spring.mail.password=304c08ac47d7b9
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.security.user.name=momo
spring.security.user.password=Avignon2024@?
#Authorization: Basic bW9tbzpEaWFsbG8xOTU3QG==

springdoc.swagger-ui.path=/api-docs
#http://localhost:8080/api-docs

server.servlet.session.cookie.same-site=None
server.servlet.session.cookie.secure=true

#server.port=8443
#server.ssl.key-store=classpath:keystore.p12
#server.ssl.key-store-password=SerigneBabacarSy1957@
#server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=dev-cert


