spring.application.name=CryptoCurrency_Project

spring.datasource.url=jdbc:sqlite:crypto_currency.db
spring.datasource.driverClassName=org.sqlite.JDBC
spring.datasource.username=momo1957
spring.datasource.password=momo1957@
spring.datasource.jpa.database-platform=org.hibernate.dialect.SQLiteDialect

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
